image: node:8.9.4

pipelines:
  branches:
    master:
      - step:
          deployment: production
          caches:
            - nodemodules
          script:
            - npm install --no-package-lock
            - npm run test
            - npm run deploy

definitions:
  caches:
    nodemodules: node_modules
